services:
  mongo-register:
    image: mongo:8.0
    container_name: register-mongo
    ports:
      - "27020:27017"
    volumes:
      - mongodata:/data/db

  register-service:
    build: .
    container_name: register-service
    ports:
      - "3005:3005"
    env_file:
      - .env
    depends_on:
      - mongo-register
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodata:
