services:
  mongo-register:
    image: mongo:8.0
    container_name: register-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      retries: 5

  register-service:
    build: .
    container_name: register-service
    depends_on:
      - mongo-register
      - rabbitmq
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodata: