services:

  gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./gateway:/app
      - /app/node_modules
    env_file:
      - ./gateway/.env
    depends_on:
      - register-service
      - target-service
      - score-service

  register-service:
    build: ./register-service
    ports:
      - "3001:3001"
    volumes:
      - ./register-service:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
      - mongo-register

  target-service:
    build: ./target-service
    ports:
      - "3002:3002"
    volumes:
      - ./target-service:/app
      - /app/node_modules
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started

  score-service:
    build: ./score-service
    ports:
      - "3003:3003"
    volumes:
      - ./score-service:/app
      - /app/node_modules
    env_file:
      - ./score-service/.env

  gui:
    build: ./gui
    container_name: gui
    ports:
      - "8080:80"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      retries: 5

  mongo-register:
    image: mongo:8
    ports:
      - "27017:27017"

  mongo-target:
    image: mongo:8
    ports:
      - "27018:27017"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
  mongo-register:
  mongo-target: