services:
  api-gateway:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      REGISTER_SERVICE_URL: http://host.docker.internal:3001
      TARGET_SERVICE_URL: http://host.docker.internal:3002