services:

  mongo:
    image: mongo:8
    container_name: target-mongo
    ports:
      # External - External
      - "27018:27017"
    volumes:
      - mongodata:/data/db

  target-service:
    build: .
    container_name: target-service
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "3002:3002"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  mongodata:
  minio_data: