services:

  mongo-target:
    image: mongo:8
    container_name: target-mongo
    ports:
      # External - Internal
      - "27018:27017"
    volumes:
      - mongodata:/data/db
      
  target-service:
    build: .
    container_name: target-service
    depends_on:
      mongo-target:
        condition: service_started
    env_file:
      - .env
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodata: