services:
  mongo-score:
    image: mongo:8.0
    container_name: score-mongo
    ports:
      - "27019:27017"
    volumes:
      - mongodata:/data/db

  score-service:
    build: .
    container_name: score-service
    env_file:
      - .env
    ports:
      - "3003:3003"
    depends_on:
      mongo-score:
        condition: service_started
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodata:
