services:
  minio-service:
    image: minio/minio
    container_name: minio-service
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - foto-global

  minio-init:
    build: ./minio-init
    container_name: minio-init
    depends_on:
      - minio-service
    environment:
      MINIO_ENDPOINT: http://minio-service:9000
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BUCKET: targets
    networks:
      - foto-global

volumes:
  minio_data:

networks:
  foto-global:
    driver: bridge